previewsEnabled: true
databases:
  - name: mysite
    databaseName: mysite
    user: mysite

services:
  - type: web
    name: mysite
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    preDeployCommand: "./bin/rails db:migrate"
    startCommand: "./bin/rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: DB_HOST
        fromDatabase:
          name: mysite
          property: host
      - key: DB_USER
        fromDatabase:
          name: mysite
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: mysite
          property: password
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
      - key: foo
        value: "bah"